In [1]:
import numpy as np

# Creating arrays

In [2]:
a = np.array([1, 2, 3]); a

array([1, 2, 3])

In [3]:
b = np.array([4, 5, 6]); b

array([4, 5, 6])

In [4]:
np.zeros((3, 4))  # Creating an array of zeros

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [5]:
np.ones((2, 3, 4))  # Create an array of ones

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [6]:
np.arange(1, 10, 2) # Create an array of evenly spaced values (step value)

array([1, 3, 5, 7, 9])

In [7]:
np.linspace(0, 1, 10)  # Create an array of evenly spaced values (number of samples)

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [8]:
np.full((3, 3), 5)  # Create an array of constants

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

In [9]:
np.eye(3)  # Create de identity matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [10]:
np.random.random((2, 2))  # Create an array with random values

array([[0.73623246, 0.50601075],
       [0.07504593, 0.35599669]])

In [11]:
np.empty((2, 2))  # Create an empty array

array([[0.73623246, 0.50601075],
       [0.07504593, 0.35599669]])

# Inspecting Numpy Arrays

In [12]:
a = np.array([[1, 2, 3],
              [4, 5, 6]])

In [13]:
a.shape  # Array dimensions

(2, 3)

In [14]:
len(a)  # Length of array

2

In [15]:
a.ndim  # Number of array dimensions

2

In [16]:
a.size  # Number of array elements

6

In [17]:
a.dtype  # Data type of array elements

dtype('int32')

In [18]:
a.dtype.name  # Name of data type

'int32'

In [19]:
a.astype(float)  # Conveting an array to a different type

array([[1., 2., 3.],
       [4., 5., 6.]])

# Array comparison

In [20]:
a = np.array([[1, 2, 3],
              [4, 5, 6]])

b = np.array([[1, 4, 3],
              [3, 5, 2]])

a == b  # Element-wise comparison

array([[ True, False,  True],
       [False,  True, False]])

In [21]:
a < 2  # Also element-wise comparison

array([[ True, False, False],
       [False, False, False]])

In [22]:
np.array_equal(a, b)  # Array-wise comparison

False

# Aggregate Functions

In [23]:
a.sum()  # Array-wise sum

21

In [24]:
a.min()  # Array-wise minimum value

1

In [25]:
a.max(axis=0)  # Maximum value of an array row

array([4, 5, 6])

In [26]:
a.cumsum(axis=1)  # Cumulative sum of the elements

array([[ 1,  3,  6],
       [ 4,  9, 15]], dtype=int32)

In [27]:
a.mean()  # Array mean

3.5

In [28]:
np.median(a)  # Median

3.5

In [29]:
np.std(a)  # Standard deviation

1.707825127659933

# Sorting Numpy Arrays

In [30]:
a = np.array([[1, 4, 3],
              [3, 5, 2]])
a

array([[1, 4, 3],
       [3, 5, 2]])

In [31]:
a.sort(); a  # Sorting an array

array([[1, 3, 4],
       [2, 3, 5]])

In [32]:
a.sort(axis=1); a  # Sort the elements of an array's axis

array([[1, 3, 4],
       [2, 3, 5]])

# Subsetting, Slicing, Indexing
## Subsetting

In [33]:
a = np.array([1, 2, 3])

In [34]:
a[2]  # Select the element at the 2nd index

3

In [35]:
a = np.array([[1, 4, 3],
              [3, 5, 2]])

In [36]:
a[1, 2]  # Select the element at row 1 column 2 (equivalent to a[1][2])

2

## Slicing

In [37]:
a[0:2, 1]  # Select items at rows 0 and 1 in column 1

array([4, 5])

In [38]:
a[:1]  # Select all items at row 0 (equivalent to a[0:1, :])

array([[1, 4, 3]])

In [39]:
a[1, ...]  # Same as [1,:,:]

array([3, 5, 2])

In [40]:
a[::-1]

array([[3, 5, 2],
       [1, 4, 3]])

## Boolean indexing

In [41]:
a

array([[1, 4, 3],
       [3, 5, 2]])

In [42]:
a[a<5]  # Select all elements that are less than 5

array([1, 4, 3, 3, 2])

# Array Manipulation

In [43]:
a

array([[1, 4, 3],
       [3, 5, 2]])

## Transposing Arrays

In [44]:
a_t = np.transpose(a); a_t  # Permute array dimensions

array([[1, 3],
       [4, 5],
       [3, 2]])

In [45]:
a.T

array([[1, 3],
       [4, 5],
       [3, 2]])

## Changing Array Shape

In [46]:
a.ravel()  # Flatten the array

array([1, 4, 3, 3, 5, 2])

In [47]:
a.reshape(3, 2)  # Reshape, but don't change the data

array([[1, 4],
       [3, 3],
       [5, 2]])

In [48]:
a.resize((3, 2)); a

array([[1, 4],
       [3, 3],
       [5, 2]])

## Adding / Removing Elements

In [49]:
a = np.array([[1, 2, 3]])
b = np.array([[4, 5, 6]])

np.append(a, b, axis=0)  # Append items to an array

array([[1, 2, 3],
       [4, 5, 6]])

In [50]:
np.insert(a, 1, 6)  # Insert items in an array

array([1, 6, 2, 3])

In [51]:
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]]); a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [52]:
np.delete(a, 1, 0)

array([[ 1,  2,  3,  4],
       [ 9, 10, 11, 12]])

In [53]:
b = np.array([[13, 14, 15, 16]])

In [54]:
print(a, b, sep='\n\n')

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

[[13 14 15 16]]


## Combining Arrays

In [55]:
np.concatenate((a, b), axis=0)  # Concatenate arrays

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [56]:
np.vstack((a, b))  # Stack arrays vertically (row-wise)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [57]:
b = np.array([[13, 14, 15]])
np.hstack((a, b.T))  # Stack arrays horizontally (column-wise)

array([[ 1,  2,  3,  4, 13],
       [ 5,  6,  7,  8, 14],
       [ 9, 10, 11, 12, 15]])

## Splitting Arrays

In [58]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [59]:
np.vsplit(a, 3)  # Split the array vertically at the 3rd index

[array([[1, 2, 3, 4]]), array([[5, 6, 7, 8]]), array([[ 9, 10, 11, 12]])]

In [60]:
np.hsplit(a, 2)  # Split the array horizontally at the 2nd index

[array([[ 1,  2],
        [ 5,  6],
        [ 9, 10]]),
 array([[ 3,  4],
        [ 7,  8],
        [11, 12]])]